//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace TerraficPlan.Mojaz2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback add_mojazOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::TerraficPlan.Properties.Settings.Default.TerraficPlan_Mojaz2_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event add_mojazCompletedEventHandler add_mojazCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_mojaz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string add_mojaz(string username, string password, string pelak, byte pelak_type, byte plan_type, byte off_type, string familyName, int mobile_num, string start_time, string end_time, int rial, string stations) {
            object[] results = this.Invoke("add_mojaz", new object[] {
                        username,
                        password,
                        pelak,
                        pelak_type,
                        plan_type,
                        off_type,
                        familyName,
                        mobile_num,
                        start_time,
                        end_time,
                        rial,
                        stations});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_mojazAsync(string username, string password, string pelak, byte pelak_type, byte plan_type, byte off_type, string familyName, int mobile_num, string start_time, string end_time, int rial, string stations) {
            this.add_mojazAsync(username, password, pelak, pelak_type, plan_type, off_type, familyName, mobile_num, start_time, end_time, rial, stations, null);
        }
        
        /// <remarks/>
        public void add_mojazAsync(string username, string password, string pelak, byte pelak_type, byte plan_type, byte off_type, string familyName, int mobile_num, string start_time, string end_time, int rial, string stations, object userState) {
            if ((this.add_mojazOperationCompleted == null)) {
                this.add_mojazOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_mojazOperationCompleted);
            }
            this.InvokeAsync("add_mojaz", new object[] {
                        username,
                        password,
                        pelak,
                        pelak_type,
                        plan_type,
                        off_type,
                        familyName,
                        mobile_num,
                        start_time,
                        end_time,
                        rial,
                        stations}, this.add_mojazOperationCompleted, userState);
        }
        
        private void Onadd_mojazOperationCompleted(object arg) {
            if ((this.add_mojazCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_mojazCompleted(this, new add_mojazCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void add_mojazCompletedEventHandler(object sender, add_mojazCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_mojazCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_mojazCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591